# hint: pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: insert-license (src)
        files: ^src/ad_hoc_diffractometer/(?!_version).*\.py$
        args:
          - --license-filepath=.copyright.txt
          - --comment-style=#
          - --no-extra-eol
      - id: insert-license
        name: insert-license (tests)
        files: ^tests/test_.*\.py$
        args:
          - --license-filepath=.copyright.txt
          - --comment-style=#
          - --no-extra-eol
      - id: insert-license
        name: insert-license (scripts)
        files: ^scripts/.*\.py$
        args:
          - --license-filepath=.copyright.txt
          - --comment-style=#
          - --no-extra-eol

  - repo: local
    hooks:
      - id: update-copyright-year
        name: Update copyright end year
        language: python
        entry: python scripts/update_copyright_year.py
        pass_filenames: false
        always_run: true

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
